/**
 * Generates a Prisma migration SQL file that seeds the Word table
 * from OpenLexicon.tsv (same processing logic as importWords.ts).
 *
 * Run once locally, then commit the generated migration file.
 *
 * Usage (from /server):
 *   npm run generate:words-migration
 */

import fs from "fs";
import path from "path";
import readline from "readline";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const TSV_PATH = path.resolve(__dirname, "OpenLexicon.tsv");
const MIGRATIONS_DIR = path.resolve(__dirname, "../../prisma/migrations");
const BATCH_SIZE = 1000;

const GUESSABLE_CGRAMS = new Set(["NOM", "ADJ", "VER", "ADV"]);
const NON_LEMME_CGRAMS = new Set(["NOM", "ADJ"]);

function normalizeWord(word: string): string {
    return word
        .toLowerCase()
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .replace(/[^a-z]/g, "");
}

interface WordEntry {
    text: string;
    length: number;
    frequency: number;
    isGuessable: boolean;
}

async function readWords(): Promise<Map<string, WordEntry>> {
    // Pass 1: collect guessable texts
    const guessableSet = new Set<string>();
    {
        const rl = readline.createInterface({
            input: fs.createReadStream(TSV_PATH, { encoding: "utf8" }),
            crlfDelay: Infinity,
        });
        let firstLine = true;
        for await (const line of rl) {
            if (firstLine) { firstLine = false; continue; }
            const cols = line.split("\t");
            if (cols.length < 8) continue;
            const cgram = cols[3]!.trim();
            const isLem = cols[7]!.trim();
            if (!GUESSABLE_CGRAMS.has(cgram) || isLem !== "1") continue;
            const normalized = normalizeWord(cols[0]!.trim());
            if (normalized.length >= 3) guessableSet.add(normalized);
        }
    }

    // Pass 2: build word map
    const wordMap = new Map<string, WordEntry>();
    {
        const rl = readline.createInterface({
            input: fs.createReadStream(TSV_PATH, { encoding: "utf8" }),
            crlfDelay: Infinity,
        });
        let firstLine = true;
        for await (const line of rl) {
            if (firstLine) { firstLine = false; continue; }
            const cols = line.split("\t");
            if (cols.length < 8) continue;
            const ortho = cols[0]!.trim();
            const lemme = cols[2]!.trim();
            const cgram = cols[3]!.trim();
            const frequency = parseFloat(cols[5]!.trim()) || 0;
            const isLem = cols[7]!.trim();
            const normalized = normalizeWord(ortho);
            if (normalized.length < 3) continue;

            if (GUESSABLE_CGRAMS.has(cgram) && isLem === "1" && guessableSet.has(normalized)) {
                const existing = wordMap.get(normalized);
                if (!existing || existing.isGuessable === false) {
                    wordMap.set(normalized, { text: normalized, length: normalized.length, frequency, isGuessable: true });
                } else if (frequency > existing.frequency) {
                    existing.frequency = frequency;
                }
                continue;
            }

            if (NON_LEMME_CGRAMS.has(cgram) && isLem === "0") {
                const normalizedLemme = normalizeWord(lemme);
                if (!guessableSet.has(normalizedLemme) || wordMap.has(normalized)) continue;
                wordMap.set(normalized, { text: normalized, length: normalized.length, frequency, isGuessable: false });
            }
        }
    }

    return wordMap;
}

function escape(s: string): string {
    return s.replace(/'/g, "''");
}

async function main() {
    if (!fs.existsSync(TSV_PATH)) {
        console.error(`TSV not found: ${TSV_PATH}`);
        process.exit(1);
    }

    console.log("Reading TSV…");
    const wordMap = await readWords();
    const entries = Array.from(wordMap.values());
    console.log(`${entries.length} words to insert`);

    // Build SQL
    const lines: string[] = [
        "-- Auto-generated by generateWordsMigration.ts — do not edit manually.",
        "-- Seeds the Word table from OpenLexicon.tsv.\n",
    ];

    for (let i = 0; i < entries.length; i += BATCH_SIZE) {
        const batch = entries.slice(i, i + BATCH_SIZE);
        const values = batch
            .map((w) => `('${escape(w.text)}',${w.length},${w.frequency},${w.isGuessable})`)
            .join(",\n    ");
        lines.push(
            `INSERT INTO games."words" (text,length,frequency,"isGuessable") VALUES\n    ${values}\nON CONFLICT (text) DO NOTHING;\n`
        );
    }

    const sql = lines.join("\n");

    // Write to a new migration directory
    const timestamp = new Date()
        .toISOString()
        .replace(/[-T:.Z]/g, "")
        .slice(0, 14);
    const migrationDir = path.join(MIGRATIONS_DIR, `${timestamp}_seed_words`);
    fs.mkdirSync(migrationDir, { recursive: true });

    const outPath = path.join(migrationDir, "migration.sql");
    fs.writeFileSync(outPath, sql, "utf8");

    const sizeKb = Math.round(fs.statSync(outPath).size / 1024);
    const guessable = entries.filter((w) => w.isGuessable).length;
    console.log(`\nMigration written → ${outPath}`);
    console.log(`  ${sizeKb} KB — ${guessable} guessable, ${entries.length - guessable} input-only`);
    console.log("\nNext steps:");
    console.log("  npx prisma migrate dev   (applies the migration locally)");
    console.log("  git add prisma/migrations && git commit");
}

main().catch((e) => { console.error(e); process.exit(1); });
